20230719 enhancement updates

diff --git a/apigeetools/lib/functions b/apigeetools/lib/functions
--- a/apigeetools/lib/functions
+++ b/apigeetools/lib/functions
@@ -1,5 +1,5 @@
 #!/bin/bash
-APIGEE_TOOLS_VERSION='4b'
+APIGEE_TOOLS_VERSION='5'
 # General approach
 #	"get..." routines will retrieve formatted individual elements of the type
 #	"get...s" routines will retrieve a list of elements of the type (TODO: change these all to "list...")
@@ -60,31 +60,12 @@ usefail() {
 	exit $RETVAL
 }
 
-debugOpts () {
-	[[ $DEBUG -eq 4 ]] && debug "PCL[dO2]: DEBUG=$DEBUG; FLAGARG=$FLAGARG"
-	case $DEBUG in 
-		0) echo -n "" > $HOME/.curlrc ; export DEBUG=0 ;;
-		1) echo -n "" > $HOME/.curlrc ; export DEBUG=1 ;;
-		2) echo "-v" > $HOME/.curlrc ; export DEBUG=2 ;;
-		3) echo "-v" > $HOME/.curlrc ; export DEBUG=3 ;;
-		4) echo "-v" > $HOME/.curlrc ; export DEBUG=4 ;;
-		5) export DEBUG=5 ; echo "5 is special true DELETE code" ;;
-		7) echo "--trace" > $HOME/.curlrc ;;
-		8) echo "--trace-ascii -" > $HOME/.curlrc ;;
-		9) echo '
-			0) "Turn Debug Off"
-			1) "Show curl command only"
-			2) "Turn Debug On (stays on until changed)"
-			3) "Debug=1 + Debug=2"
-			4) "Include function library in debug"
-			5) "Issue true DELETE (otherwise runs a GET)"
-			7) "Adds --trace to $HOME/.curlrc"
-			8) "Adds --trace-ascii - to $HOME/.curlrc"
-			9) "Show this DEBUG Help"
-			*) "Invalid DEBUG LEVEL"'  ; DEBUG=0 ; exit 1 ;;
-		*) echo -en "\n\n Invalid DEBUG LVL: $DEBUG \n\n" ; exit 1 ;;
-	esac
-	[[ $DEBUG -eq 4 ]] && debug "PCL[dO3]: DEBUG=$DEBUG; FLAGARG=$FLAGARG"
+findEnv() {  # No longer used??
+	[[ $DEBUG -eq 4 ]] && debug "Called findEnv $1"
+    if [ "_$1" == "_" ]; then
+		usefail "no host specified"
+    fi
+	find -L ${TOOLSDIR} -name "$1"
 }
 
 loadConfig() {
@@ -119,164 +100,197 @@ loadConfig() {
 }
 
 checkArgs() {
-	[[ $DEBUG -eq 4 ]] && debug "[checkArgs]: ARGS= $@"
+	[[ $DEBUG -eq 4 ]] && debug "[checkArgs]: ARGS= $ARGS"
 	# [[ "${ARGS[0]}_" == "_" ]] && usefail "Missing Argument(s)"
 	# [[ "$1_" == "_" ]] && usefail "Missing Argument(s)"
 	loadConfig
 }
 
-parseCommandline() {
+debugOpts () {
+	case $DEBUG in 
+		0) echo -n "" > $HOME/.curlrc ; export DEBUG=0 ;;
+		1) echo -n "" > $HOME/.curlrc ; export DEBUG=1 ;;
+		2) echo "-v" > $HOME/.curlrc ; export DEBUG=2 ;;
+		3) echo -n "" > $HOME/.curlrc ; export DEBUG=3 ;;
+		4) echo -n "" > $HOME/.curlrc ; export DEBUG=4 ;;
+		5) export DEBUG=5 ; echo "5 is special true DELETE code" ;;
+		7) echo "--trace" > $HOME/.curlrc ;;
+		8) echo "--trace-ascii -" > $HOME/.curlrc ;;
+		9) echo '
+			0) "Turn Debug Off"
+			1) "Show curl command only"
+			2) "Turn Debug On"
+			3) "Debug=1 + Debug=2"
+			4) "Include function library in debug"
+			5) "Issue true DELETE (otherwise runs a GET)"
+			7) "Adds --trace to $HOME/.curlrc"
+			8) "Adds --trace-ascii - to $HOME/.curlrc"
+			9) "Show this DEBUG Help"
+			*) "Invalid DEBUG LEVEL"'  ; DEBUG=0 ; exit 1 ;;
+		*) echo -en "\n\n Invalid DEBUG LVL: $DEBUG \n\n" ; exit 1 ;;
+	esac
+}
 
-	[[ $DEBUG -eq 4 ]] && debug "PCL[test2-1]: OPTS & ARGS=$ARGS; \$@= $@";
-	ARGS=""
-	FLAG_ARG=""
+parseCommandline() {
+	PPRAMS=""
+	NUMOPTS=0
+	ARGNO=0
+	[[ $DEBUG -eq 4 ]] && debug "PCL[0]: ARGS=${ARGS}; NO=$NUMOPTS; PPRAMS=${PPRAMS}; \$1=$1; \$2=$2"
 
 	while (( "$#" )); do
-		FLAGARG=""
-		if [ "${2:0:1}" != "-" ]; then
-			FLAGARG=$2
-		fi
-		[[ $DEBUG -eq 4 ]] && debug "PCL[0]: OPT=$1 FLAGARG=$FLAGARG";
-
 		case "$1" in
-		-d|--debug)
-			[[ $DEBUG -eq 4 ]] && debug "PCL[d1]: DEBUG=$DEBUG; FLAGARG=$FLAGARG"
+
+		-d[1-9]|--debug)
 			
 			echo "" > $HOME/.curlrc
 			DEBUG=0
+			FLAGARG=""
+
+			[[ $DEBUG -eq 4 ]] && debug "\${1:2:3}=${1:2:3}"
+			if [[ ${1:2:3} = [0-9] ]]; then
+				FLAGARG=${1:2:3}
+				[[ $DEBUG -eq 4 ]] && debug "PCL[-d]: FLAGARG=${FLAGARG}"
+				NUMOPTS+=1
+				shift 				
+
+			elif [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+				FLAGARG=$2
+				NUMOPTS+=2
+				shift 2
+
+			else
+				FLAGARG=9
+				echo "Error: Argument for $1 is missing" >&2
+			fi
+
 			if [[ "$FLAGARG" ]]; then
-				DEBUG=${FLAGARG}
-				echo '-v' > $HOME/.curlrc
-			else 
-				export DEBUG=1
+				export DEBUG=${FLAGARG}
+				[[ $DEBUG -eq 2 ]] && echo '-v' > $HOME/.curlrc
 			fi
 
 			debugOpts
-			# [[ $DEBUG -eq 4 ]] && 
-				debug "PCL[d1end]: DEBUG=$DEBUG; FLAGARG=$FLAGARG"
+
+			# [[ $DEBUG -ge 2 ]] && 
+			debug "PCL[-d]: FLAGARG=$FLAGARG "
 			;;
-		-e)
-			export ENVIRONMENT=$FLAGARG
-			[[ $DEBUG -eq 4 ]] && debug "PCL[-e]: ENVIRONMENT=$FLAGARG"
+
+		-e) # set environment
+			FLAGARG=""
+			if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+				FLAGARG=$2
+				NUMOPTS+=2
+				shift 2
+			else
+				echo "Error: Argument for $1 is missing" >&2
+				exit 1
+			fi
+			if [[ "$FLAGARG" ]]; then
+				export ENVIRONMENT=$FLAGARG
+			fi
+			[[ $DEBUG -eq 4 ]] && debug "PCL[-e]: ENVIRONMENT=$ENVIRONMENT"
 			;;
-		-h|--help) 
-			[[ $DEBUG -eq 4 ]] && debug "PCL[-help]: ORGANIZATION=$ORGANIZATION"
+
+		-h|--help) # help
 			usage
 			exit 0
 			;;
-		-j)
+
+		-j) # set format to json (default)
 			FRMT=json
+			NUMOPTS+=1
+			shift
 			[[ $DEBUG -eq 4 ]] && debug "PCL[-j]: FRMT=$FRMT"
 			;;
-		-l)
+
+		-l) # set TRUE Delete
 			export DEBUG=5 # Special option for "True" delete
+			NUMOPTS+=1
+			shift
 			[[ $DEBUG -eq 4 ]] && debug "PCL[-l]: DEBUG=$DEBUG"
 			;;
-		-o)
-			export ORGANIZATION=$FLAGARG
+
+		-o) # set organization
+			FLAGARG=""
+			if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+				FLAGARG=$2
+				NUMOPTS+=2
+				shift 2
+			else
+				echo "Error: Argument for $1 is missing" >&2
+				exit 1
+			fi
+			if [[ "$FLAGARG" ]]; then
+				export ORGANIZATION=$FLAGARG
+			fi
 			[[ $DEBUG -eq 4 ]] && debug "PCL[-o]: ORGANIZATION=$ORGANIZATION"
 			;;
-		-v)
+
+		-v) # print version
 		    version
 		    exit 0
 		    ;;
-		-x)
+
+		-x) # set format to XML
 			FRMT=xml
+			NUMOPTS+=1
+			shift
 			[[ $DEBUG -eq 4 ]] && debug "PCL[-x]: FRMT=$FRMT"
 			;;
-		*)
-			[[ $DEBUG -eq 4 ]] && debug "PCL[*]: ARGS=$ARGS"
-			ARGS="$ARGS $1"
+
+		-*|--*) # unsupported flags
+			echo "Error: Unsupported flag $1" >&2
+			exit 1
+			;;
+
+		*)	PPRAMS="$PPRAMS $1"
+			# ARGS="${ARGS[${ARGNO}]} $1"
+			# ARGNO+=1
+			# [[ $DEBUG -eq 4 ]] && debug "PPRAMS= ${PPRAMS}; ARGS= ${ARGS}"
+			shift
 			;;
 		esac
 
-		[[ $DEBUG -eq 4 ]] && debug "PCL[endloop-bs]: OPT=$1  FLAGARG=$2"
-		shift
-		[[ $DEBUG -eq 4 ]] && debug "PCL[endloop-as]: OPT=$1  FLAGARG=$2"
-
-		[[ "$1" && !("$2") ]] && ARGS="$ARGS $1"
-
-		[[ "$FLAGARG" ]] && shift
-		FLAGARG=""
-		[[ $DEBUG -eq 4 ]] && debug "PCL[endloop-as2]: OPT=$1  FLAGARG=$2  \$3=$3"
+		[[ $DEBUG -eq 4 ]] && debug "PCL[endloop]: ARGS=[${ARGS}]; NO=$NUMOPTS; PPRAMS=[${PPRAMS}]; \$1=$1; \$2=$2"
 	done
 
 	[[ $DEBUG -eq 4 ]] && 
-		debug "PCL[4a-set] Before eval : ARGS=${ARGS} \$@=$@"
+		debug "PCL[4a-set] Before read ARGS -- PPRAMS= $PPRAMS: NO=$NUMOPTS; \$1=$1; \$2=$2 \$@=$@"
 
-	eval set -- "$ARGS"
-	[[ $DEBUG -eq 4 ]] && 
-		debug "PCL[4b-set] After eval : ARGS=${ARGS} \$@=$@"
+	# local IFS=', \n\r\t'; read -r -a ARGS <<< "$PPRAMS"
+	read -r -a ARGS <<< "$PPRAMS";
 
-	# OFS=$IFS;IFS=', \n\r\t'; read -r -a ARGS <<< "$ARGS";IFS=$OFS
-	local IFS=', '; read -r -a ARGS <<< "$ARGS"
-	[[ $DEBUG -eq 4 ]] && 
-		debug "PCL[4c-set] After read : ARGS=${ARGS} \$@=$@"
-}
-
-parseCommandline2 () {
-	PARAMS=""
-	while (( "$#" )); do
-	  case "$1" in
-	    -a|--my-boolean-flag)
-	      MY_FLAG=0
-	      shift
-	      ;;
-	    -b|--my-flag-with-argument)
-	      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
-	        MY_FLAG_ARG=$2
-	        shift 2
-	      else
-	        echo "Error: Argument for $1 is missing" >&2
-	        exit 1
-	      fi
-	      ;;
-	    -*|--*=) # unsupported flags
-	      echo "Error: Unsupported flag $1" >&2
-	      exit 1
-	      ;;
-	    *) # preserve positional arguments
-	      PARAMS="$PARAMS $1"
-	      shift
-	      ;;
-	  esac
-	done
-	# set positional arguments in their proper place
-	eval set -- "$PARAMS"
-
-}
-
-findEnv() {  # No longer used??
-	[[ $DEBUG -eq 4 ]] && debug "Called findEnv $1"
-    if [ "_$1" == "_" ]; then
-		usefail "no host specified"
-    fi
-	find -L ${TOOLSDIR} -name "$1"
+	[[ $DEBUG -eq 4 ]] && debug "PCL[end]: NOPTS=${NUMOPTS} PPrams=${PPRAMS}; ARGS=${ARGS}; \$@=$@"
 }
 
 rest() {
 	# All calls to rest must supply a Verb and a fully qualified URL 
 	#   (Headers, output format; and curl options are specified in caller routine)
-	#   (Output includes response and status code)
+	#   (Output includes RESPONSE and STATUS_CODE)
+
 	local VERB=$1
 	local URL=$2
+	STATUS_CODE=0
+	RESPONSE=""
+
 	if [ "$FRMT" != "xml" -a "$FRMT" != "json" ] ; then
 		FRMT=json
 		[[ $DEBUG -eq 4 ]] && debug "rest: No FRMT [$FRMT] - setting to 'json'"
 	fi
+	
 	local ACCPT="application/$FRMT"
-	#local ACCPT="*/*"
+	# local ACCPT="*/*"
 
-	[[ $DEBUG -eq 4 ]] && debug "rest[1] VERB=$VERB; URL=$URL; Headers: $HDRS ; curlOPTS: $curlOPTS ; ~/.curlrc = [`cat $HOME/.curlrc`]"
+	[[ $DEBUG -ge 3 ]] && debug "rest[1] VERB=$VERB; URL=$URL; Headers: $HDRS ; curlOPTS: $curlOPTS ; ~/.curlrc = [`cat $HOME/.curlrc`]"
 
-	# set -x
+	[[ $DEBUG -ge 6 ]] && set -x
 
 	case $VERB in
 		"DELETE") ;;
 		"GET") ;;
 		"POST")
 			[[ "$HDRS" != *"Content-Type"* ]] && HDRS="-HContent-Type:application/${FRMT} ${HDRS}"
-			#[[ "$HDRS" != *"Content-Length"* ]] && HDRS="-HContent-Length:0 ${HDRS}"
+			# [[ "$HDRS" != *"Accept"* ]] && HDRS="-HAccept:$ACCPT ${HDRS}"
+			# [[ "$HDRS" != *"Content-Length"* ]] && HDRS="-HContent-Length:0 ${HDRS}"
 			[[ $DEBUG -ge 3 ]] && debug "rest [POST] Headers: $HDRS ; curlOPTS: $curlOPTS ; ~/.curlrc = [`cat $HOME/.curlrc`]"
 			;;
 		*) fail "Invalid VERB=[$VERB] for curl call" ;;
@@ -286,13 +300,14 @@ rest() {
 
 	SHOWCURL="false"
 	[[ $DEBUG -ge 1 ]] && SHOWCURL=true
-	[[ $DEBUG -ge 4 ]] && echo "rest[4] SHOWCURL= $SHOWCURL ; DEBUG= $DEBUG"
+	[[ $DEBUG -ge 4 ]] && debug "rest[4] SHOWCURL= $SHOWCURL ; DEBUG= $DEBUG"
 
-	# Non .netrc version
+	# MAKE THE CURL CALL!
+
+	# Non .netrc version (requires CREDENTIALS=username":"password)
 	#local output=$([ "$DEBUG" != "false" ] && set -x;curl -sSu "$CREDENTIALS" -X $VERB -H "Accept: $ACCPT" -w "\n%{http_code}\n" "${URL}" ${HDRS} ${curlOPTS};set -)
 
 	# .netrc version
-	# MAKE THE CURL CALL!
 	local output=$(
 		set -
 		$SHOWCURL && set -x
@@ -300,35 +315,39 @@ rest() {
 		set -
 	)
 
+	# [TMD] Trying something new... turn off curl -v after everycall
+	echo "" >~/.curlrc
+
 	if [ "$output" != "" ] ; then
+		[[ $DEBUG -ge 4 ]] && debug "[rest]: Output= \n$output"
+
 		STATUS_CODE=`echo "$output" | tail -n 1`
 		rawRESPONSE=`echo "$output" | sed '$ d'`
 
 		case $STATUS_CODE in
 			"200"|"201")  # TODO: Need to do this as a "SUCCESS_CODES" list
-				#echo -e "CURL Succeeded: STATUS_CODE= $STATUS_CODE"
-				[[ $DEBUG -ge 1 ]] && debug "CURL Succeeded: STATUS_CODE= $STATUS_CODE"
+				if [ "$FRMT" = "json" ] && [ "$rawResponse" != "" ] ; then
+					RESPONSE=`echo "$rawRESPONSE" | "$TOOLSDIR/lib/jp.sh"`
+					[[ $DEBUG -ge 4 ]] && debug "rest: \n\tRESPONSE= \n$RESPONSE\n\t"
+				else
+					RESPONSE=`echo "$rawRESPONSE"`
+					[[ $DEBUG -ge 4 ]] && debug "rest: \n\tRESPONSE= \n$RESPONSE\n\t"
+				fi
+				[[ $DEBUG -ge 4 ]] && debug "CURL call Succeeded: "
 				;;
-			*) 	echo $output > fail.out
+
+			*) 	echo $output > ~/tmp/fail.out
 				fail "CURL call failed: STATUS_CODE= [$STATUS_CODE]"
 				;;
 		esac
-
-		if [ "$FRMT" = "json" ] && [ "$rawResponse" != "" ] ; then
-			RESPONSE=`echo "$rawRESPONSE" | "$TOOLSDIR/lib/jp.sh"`
-			[[ $DEBUG -eq 4 ]] && debug "rest: STATUS_CODE [${STATUS_CODE}]: \n\tRESPONSE= \n$RESPONSE\n\n\t"
-		else
-			RESPONSE=`echo "$rawRESPONSE"`
-			[[ $DEBUG -eq 4 ]] && debug "rest: STATUS_CODE [${STATUS_CODE}]: \n\tRESPONSE= \n$RESPONSE\n\n\t"
-		fi
 	else
-		fail "CURL call failed: Output= $output"
+		fail "CURL call failed: Output= {$output} N/A"
 	fi
 
-	[[ $DEBUG -eq 4 ]] && debug "\n\tRawOutput= \n$output\n\t"
+	[[ $DEBUG -ge 3 ]] && debug "rest: \n\tRawOutput= \n$output\n\t"
 
-	# Should use this, but must remove lots of other "echo" commands
-	#[[ "_$ENVIRONMENT" != "_" ]] && echo $RESPONSE
+	# echo "$STATUS_CODE"
+	# return "$STATUS_CODE"
 }
 
 http_get() {
@@ -336,7 +355,7 @@ http_get() {
 }
 
 http_post() {
-	rest POST $@
+	return `rest POST $@`
 }
 
 http_delete() {
@@ -376,17 +395,17 @@ xmlValueOf() {
 
 jsonValueOf() {
 	local field=$1
-	echo "BEGIN { RS = \"[\\n\\r]+\" } ; /${field}/ {print \$2}" >awk.inf
-	[[ $DEBUG -eq 4 ]] && debug "jsonValueOf ${field} from stream `cat awk.inf`"
-	awk -f awk.inf -
+	echo "BEGIN { RS = \"[\\n\\r]+\" } ; /${field}/ {print \$2}" > ~/tmp/awk.inf
+	[[ $DEBUG -eq 4 ]] && debug "jsonValueOf ${field} from stream `cat ~/tmp/awk.inf`"
+	awk -f ~/tmp/awk.inf -
 }
 
 jsonValueSet() {
 	local field=$1
 	local value=$2
-	echo "BEGIN { RS = \"[\\n\\r]+\" } ; /${field}/ {print \$2}" >awk.inf
-	[[ $DEBUG -ge 4 ]] && debug "jsonValueOf $field from stream `cat awk.inf`"
-	awk -f awk.inf -
+	echo "BEGIN { RS = \"[\\n\\r]+\" } ; /${field}/ {print \$2}" > ~/tmp/awk.inf
+	[[ $DEBUG -ge 4 ]] && debug "jsonValueOf $field from stream `cat ~/tmp/awk.inf`"
+	awk -f ~/tmp/awk.inf -
 	sed 's/\("name"[:, "]*$field'
 }
 
